engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
exclude_paths:
- app/third_party/MX/**/*
- data/**/*
